

@startuml
' Asana Plus como plataforma
hide empty members
    abstract class Usuario {
        id
        nombre
        email
    }

    class Proyecto {
        nombre
    }

    class Sprint {
        fechaInicio
        fechaFin
    }

    class HistoriaDeUsuario {
        descripcion
        puntosHistoria
        estado
        fechaFinalizacion
    }

    class Subtarea {
        descripcion
        estado
    }

    class RegistroDeHoras {
        horas
        fecha
    }
    
    class Administrador
    {
    }

    class Equipo {
        nombre
    }
    
    class Asana {
    }
    
    class Estadística {
    }
    
    class Gráfica{
    }
    

    
    
    Proyecto "1" o-- "N" Sprint : contiene
    Proyecto "1" *-- "N" Asana : contiene
    Asana  .right.  Usuario 
    Sprint "1" o-left- "N" HistoriaDeUsuario : contiene
    HistoriaDeUsuario "1" o-- "N" Subtarea : compuestaPor
    Usuario <|-- Administrador

    Equipo "1" o-- "N" Usuario : contiene
    Equipo -left Proyecto : tiene

    Usuario "1" o-- "N" HistoriaDeUsuario : asignadoA
    Subtarea "1" o-- "N" RegistroDeHoras : contiene
    Subtarea  --  Usuario : realizadaPor
    HistoriaDeUsuario  --> Estadística : analiza
    Estadística  -- Gráfica : produce

}

@enduml
