@startuml
' Modelo de Dominio de Presupuesto (ajustado)
package "Presupuesto" {
class Presupuesto {

}

class Proyecto {

}

class Dinero {

}

class Fase {

}

class Actividad {

}

class RRHH {

}

class Horas {

}

class Ingreso {

}

class Egreso {

}


Presupuesto --> Proyecto : "Tiene"
Presupuesto --> Dinero : "Tiene"

Proyecto --> Fase : "Compuesto por"
Fase --> Actividad : "Incluye"
Fase --> Dinero : "Asignado"

Actividad --> RRHH: "Asignado a"
Actividad --> Horas : "Consume"
Horas --> Dinero : "Costean"

Dinero --> Ingreso : "Incluye"
Dinero --> Egreso : "Incluye"
}
@enduml
