@startuml
title Casos de uso – Administrador
left to right direction

actor "Administrador" as Admin

rectangle "Asana Plus" as Sistema {

  package "Analítica" {
    usecase "Ver Gráficas" 
    usecase "Exportar el StoryPoint"
  }
  
    package "Proyectos" {
    usecase "Listar Tareas" 
    usecase "Listar Sprints" 
    usecase "Sincronizar con Asana" 
  }
    package "Autenticación" {
    usecase "Cerrar sesión"
    usecase "Iniciar sesión"
  }
  
  
}

' Enlaces solo del Administrador
Admin --> Autenticación
Proyectos <-- Admin
Admin --> Analítica

@enduml
