@startuml
title Casos de uso – Tiempo
left to right direction

actor "Tiempo" as Tiempo


  package "Gestión de Proyectos" {
    usecase "listarHistoriasDeUsuario()" 
    usecase "listarSprints()" 
    usecase "sincronizarAsana()"

}
Tiempo --> "listarHistoriasDeUsuario()"
Tiempo --> "listarSprints()"
Tiempo --> "sincronizarAsana()"

@enduml
