
@startuml

class Menu
class ElementoMenu
class Precio
class Descripcion
class Ingredientes
class Persona
class Chef
class Cliente

hide empty members
hide circle

Menu --* ElementoMenu: Contiene

ElementoMenu --* Precio: Tiene
ElementoMenu --* Descripcion: Incluye
ElementoMenu --* Ingredientes: Hecho de

Descripcion --|>  Ingredientes: Incluye

Persona --* Chef
Persona --* Cliente

Chef --|> ElementoMenu : Prepara
Cliente --> Menu: Recibe
Cliente --> ElementoMenu: Pide

@enduml
