@startuml

rectangle "Receta" as Receta
rectangle "Resultado" as Resultado
rectangle "Ingredientes" as Ingredientes
rectangle "Procedimiento" as Procedimiento
rectangle "Utensilios" as Utensilios
rectangle "Pasos" as Pasos
rectangle "Condiciones" as Condiciones
rectangle "Actividad" as Actividad

Receta -- Resultado : busca >
Receta -- Procedimiento : es >
Procedimiento -- Pasos : son >
Procedimiento -- Ingredientes : tiene >
Procedimiento -- Utensilios : tiene >
Pasos -- Condiciones : tiene >
Pasos -- Actividad : es >
Actividad -- Ingredientes : tiene >
Actividad -- Utensilios : tiene >

@enduml