@startuml
[*] --> Creacion

Creacion --> Creacion : agregarIngredientes()
Creacion --> ListoParaPublicar : recetaCompleta()
ListoParaPublicar --> Publicada : publicar()
Publicada --> Archivada : archivar()
Archivada --> Creacion : restaurar() 

@enduml
